package io.github.knaitoe.theoldesthouse.client;
import io.github.knaitoe.theoldesthouse.TheOldestHouse;
import io.github.knaitoe.theoldesthouse.labyrinth.*;
import com.mojang.blaze3d.vertex.*;
import com.mojang.math.Axis;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.*;
import net.minecraft.client.model.geom.*;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.renderer.*;
import net.minecraft.client.renderer.blockentity.*;
import net.minecraft.client.renderer.entity.*;
import net.minecraft.core.*;
import net.minecraft.nbt.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.EntityRenderersEvent;
/** Tailored, posed human cast, antlerless cow elk and bounded native fan/miniature renderers. */
@EventBusSubscriber(modid=TheOldestHouse.MOD_ID,bus=EventBusSubscriber.Bus.MOD,value=Dist.CLIENT)
public final class LiteraryRenderers {
    public static final ModelLayerLocation CAST=layer("literary_cast"),ELK=layer("literary_elk"),FAN=layer("literary_fan");
    private static ModelLayerLocation layer(String name){return new ModelLayerLocation(ResourceLocation.fromNamespaceAndPath(TheOldestHouse.MOD_ID,name),"main");}
    private static ResourceLocation texture(String name){return ResourceLocation.fromNamespaceAndPath(TheOldestHouse.MOD_ID,"textures/entity/literary_"+name+".png");}
    public static ResourceLocation skin(int role,int phase){String[] roles={"mother","dancer","red_figure","coffin_woman","lady","silhouette","brother","father","visitor","killer","family_father","family_mother","family_child","old_man","stranger","camera"};String name=roles[Math.max(0,Math.min(15,role))];if(role==LiteraryActor.STRANGER)name+="_"+Math.min(3,phase);else if(role==LiteraryActor.SILHOUETTE&&phase>0)name+="_"+Math.min(3,phase);else if(role==LiteraryActor.FATHER&&phase>=2)name+="_bandaged";else if(role>=LiteraryActor.FAMILY_FATHER&&role<=LiteraryActor.FAMILY_CHILD&&phase>0)name+="_changed";return texture(name);}
    @SubscribeEvent public static void layers(EntityRenderersEvent.RegisterLayerDefinitions e){e.registerLayerDefinition(CAST,CastModel::layer);e.registerLayerDefinition(ELK,ElkModel::layer);e.registerLayerDefinition(FAN,ModelRenderer::fanLayer);}
    @SubscribeEvent public static void renderers(EntityRenderersEvent.RegisterRenderers e){e.registerEntityRenderer(LiteraryRegistry.ACTOR.get(),CastRenderer::new);e.registerEntityRenderer(LiteraryRegistry.ELK.get(),ElkRenderer::new);e.registerBlockEntityRenderer(LiteraryRegistry.MODEL.get(),ModelRenderer::new);}
    public static final class CastModel extends HumanoidModel<LiteraryActor>{private final ModelPart coat,gown,mask,bandage,hood;
        public CastModel(ModelPart r){super(r);coat=body.getChild("coat");gown=body.getChild("gown");mask=head.getChild("mask");bandage=leftLeg.getChild("bandage");hood=head.getChild("hood");}
        public static LayerDefinition layer(){var m=HumanoidModel.createMesh(CubeDeformation.NONE,0);var r=m.getRoot();r.getChild("body").addOrReplaceChild("coat",CubeListBuilder.create().texOffs(64,28).addBox(-4.4F,1,-2.4F,8.8F,17,4.8F),PartPose.ZERO);r.getChild("body").addOrReplaceChild("gown",CubeListBuilder.create().texOffs(96,28).addBox(-5.2F,9,-3.2F,10.4F,14,6.4F),PartPose.ZERO);r.getChild("head").addOrReplaceChild("mask",CubeListBuilder.create().texOffs(64,0).addBox(-4.15F,-8.2F,-4.5F,8.3F,8.5F,1),PartPose.ZERO);r.getChild("head").addOrReplaceChild("hood",CubeListBuilder.create().texOffs(82,0).addBox(-4.4F,-8.4F,-4.4F,8.8F,8.8F,8.8F),PartPose.ZERO);r.getChild("left_leg").addOrReplaceChild("bandage",CubeListBuilder.create().texOffs(112,0).addBox(-2.2F,5,-2.2F,4.4F,5,4.4F),PartPose.ZERO);r.addOrReplaceChild("herd_eyes",CubeListBuilder.create().texOffs(0,0).addBox(-4,0,0,1,1,1).addBox(3,0,0,1,1,1),PartPose.ZERO);return LayerDefinition.create(m,128,64);}
        public void pose(int role,int phase,float age){coat.visible=role==LiteraryActor.FAMILY_FATHER||role==LiteraryActor.OLD_MAN||role==LiteraryActor.VISITOR||role==LiteraryActor.STRANGER;gown.visible=role==LiteraryActor.LADY||role==LiteraryActor.COFFIN_WOMAN||role==LiteraryActor.FAMILY_MOTHER;mask.visible=role==LiteraryActor.DANCER||role==LiteraryActor.RED_FIGURE||role==LiteraryActor.KILLER;hood.visible=role==LiteraryActor.KILLER;bandage.visible=role==LiteraryActor.FATHER&&phase>=2;
            if(role==LiteraryActor.DANCER&&phase==1){leftArm.xRot=rightArm.xRot=-.8F;leftArm.zRot=-.55F;rightArm.zRot=.55F;body.yRot=(float)Math.sin(age*.045)*.18F;leftLeg.xRot=(float)Math.sin(age*.08)*.22F;rightLeg.xRot=-leftLeg.xRot;}
            if(role==LiteraryActor.OLD_MAN){body.xRot=.19F;head.xRot=.14F;leftArm.xRot=rightArm.xRot=-.1F;}
            if(role==LiteraryActor.FATHER&&phase>=2){leftLeg.xRot=.25F;leftLeg.zRot=.06F;body.zRot=-.06F;rightArm.zRot=.2F;}
            if(role==LiteraryActor.BROTHER&&phase>0){leftArm.xRot=rightArm.xRot=-.18F;head.xRot=.4F;}
        }
        @Override public void setupAnim(LiteraryActor a,float walk,float amount,float age,float yaw,float pitch){head.getAllParts().forEach(ModelPart::resetPose);body.getAllParts().forEach(ModelPart::resetPose);leftLeg.getAllParts().forEach(ModelPart::resetPose);rightLeg.resetPose();leftArm.resetPose();rightArm.resetPose();super.setupAnim(a,walk,amount,age,yaw,pitch);pose(a.role(),a.phase(),age);}
    }
    private static final class CastRenderer extends MobRenderer<LiteraryActor,CastModel>{private final ModelPart eyes;CastRenderer(EntityRendererProvider.Context c){super(c,new CastModel(c.bakeLayer(CAST)),.2F);eyes=c.bakeLayer(CAST).getChild("herd_eyes");}@Override public void render(LiteraryActor a,float yaw,float partial,PoseStack p,MultiBufferSource out,int light){if(a.role()==LiteraryActor.RED_FIGURE&&a.phase()==3){p.pushPose();p.translate(0,1.45,0);p.mulPose(Axis.YP.rotationDegrees(-yaw));eyes.render(p,out.getBuffer(RenderType.eyes(texture("herd_eyes"))),LightTexture.FULL_BRIGHT,net.minecraft.client.renderer.texture.OverlayTexture.NO_OVERLAY);p.popPose();return;}super.render(a,yaw,partial,p,out,light);}@Override public ResourceLocation getTextureLocation(LiteraryActor a){return skin(a.role(),a.phase());}@Override protected void setupRotations(LiteraryActor a,PoseStack p,float age,float yaw,float partial,float scale){super.setupRotations(a,p,age,yaw,partial,scale);if(a.role()==LiteraryActor.COFFIN_WOMAN&&a.phase()==1){p.translate(0,.25,0);p.mulPose(Axis.ZP.rotationDegrees(90));}if(a.role()==LiteraryActor.BROTHER&&a.phase()>0){p.mulPose(Axis.ZP.rotationDegrees(90));}}@Override public boolean shouldRender(LiteraryActor a,net.minecraft.client.renderer.culling.Frustum f,double x,double y,double z){var p=Minecraft.getInstance().player;return (a.scene().equals(LabyrinthPlace.FAMILY_COPY.id())||a.scene().equals(LabyrinthPlace.OLD_CABIN.id())||a.owner().isEmpty()||p!=null&&a.owner().get().equals(p.getUUID()))&&super.shouldRender(a,f,x,y,z);}}
    public static final class ElkModel extends EntityModel<LiteraryElk>{private final ModelPart root;public ElkModel(ModelPart r){root=r;}
        public static LayerDefinition layer(){var m=new MeshDefinition();var r=m.getRoot();r.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-5,-6,-10,10,12,23),PartPose.offset(0,11,0));r.addOrReplaceChild("neck",CubeListBuilder.create().texOffs(50,0).addBox(-3.5F,-6,-4,7,15,8),PartPose.offsetAndRotation(0,7,-9,-.4F,0,0));var h=r.addOrReplaceChild("head",CubeListBuilder.create().texOffs(80,0).addBox(-3.8F,-3.5F,-8,7.6F,7,10).texOffs(80,20).addBox(-2.8F,0,-12,5.6F,4,5),PartPose.offset(0,3,-12));h.addOrReplaceChild("ear_left",CubeListBuilder.create().texOffs(112,0).addBox(0,-2,-1,6,3,2),PartPose.offsetAndRotation(3,-2,0,0,0,-.4F));h.addOrReplaceChild("ear_right",CubeListBuilder.create().texOffs(112,0).addBox(-6,-2,-1,6,3,2),PartPose.offsetAndRotation(-3,-2,0,0,0,.4F));for(int i=0;i<4;i++)r.addOrReplaceChild("leg"+i,CubeListBuilder.create().texOffs(0,38).addBox(-1.5F,0,-1.5F,3,13,3).texOffs(14,38).addBox(-1.8F,11,-2,3.6F,2,4),PartPose.offset(i%2==0?-3.5F:3.5F,11,i<2?-7:9));r.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(28,38).addBox(-1,-1,0,2,2,5),PartPose.offsetAndRotation(0,8,12,.2F,0,0));return LayerDefinition.create(m,128,64);}
        @Override public void setupAnim(LiteraryElk a,float walk,float amount,float age,float yaw,float pitch){root.getAllParts().forEach(ModelPart::resetPose);root.getChild("head").yRot=yaw*.01745F;root.getChild("head").xRot=pitch*.01745F;for(int i=0;i<4;i++)root.getChild("leg"+i).xRot=(float)Math.cos(walk*.6662F+(i==0||i==3?0:Math.PI))*amount*.8F;}
        public void lying(){root.getAllParts().forEach(ModelPart::resetPose);for(int i=0;i<4;i++)root.getChild("leg"+i).xRot=-.6F;}
        @Override public void renderToBuffer(PoseStack p,VertexConsumer b,int light,int overlay,int color){root.render(p,b,light,overlay,color);}}
    private static final class ElkRenderer extends MobRenderer<LiteraryElk,ElkModel>{ElkRenderer(EntityRendererProvider.Context c){super(c,new ElkModel(c.bakeLayer(ELK)),.5F);}@Override public ResourceLocation getTextureLocation(LiteraryElk a){return texture(a.wounded()?"elk_wounded":"elk");}}
    public static final class ModelRenderer implements BlockEntityRenderer<LiteraryModelBlockEntity>{private final ModelPart fan;private final ElkModel elk;private final HumanoidModel<?> tiny;
        public ModelRenderer(BlockEntityRendererProvider.Context c){fan=c.bakeLayer(FAN);elk=new ElkModel(c.bakeLayer(ELK));tiny=new HumanoidModel<>(c.bakeLayer(ModelLayers.PLAYER));}
        public static LayerDefinition fanLayer(){var m=new MeshDefinition();var r=m.getRoot();r.addOrReplaceChild("hub",CubeListBuilder.create().texOffs(0,0).addBox(-3,-2,-3,6,4,6),PartPose.ZERO);for(int i=0;i<4;i++)r.addOrReplaceChild("blade"+i,CubeListBuilder.create().texOffs(24,0).addBox(2,-1,-2,22,1.5F,4),PartPose.rotation(0,(float)(i*Math.PI/2),.025F));return LayerDefinition.create(m,128,64);}
        @Override public void render(LiteraryModelBlockEntity e,float partial,PoseStack p,MultiBufferSource out,int light,int overlay){var state=e.getBlockState();if(state.is(LiteraryRegistry.FROZEN.get())){var original=LiteraryFrozenBlock.original(e.getLevel(),e.getBlockPos());if(!original.isAir())Minecraft.getInstance().getBlockRenderer().renderSingleBlock(original,p,out,light,overlay);return;}if(!state.is(LiteraryRegistry.PROP.get()))return;var kind=state.getValue(LiteraryPropBlock.KIND);var mc=Minecraft.getInstance();if(mc.player==null)return;
            if(kind==LiteraryPropBlock.Kind.FAN){float age=e.getLevel()==null?0:e.getLevel().getGameTime()+partial;float angle=age*.6F;p.pushPose();p.translate(.5,.72,.5);p.mulPose(Axis.YP.rotation(angle));fan.render(p,out.getBuffer(RenderType.entityCutoutNoCull(texture("fan"))),light,overlay);p.popPose();double height=mc.player.getEyeY()-e.getBlockPos().getY();if(mc.options.getCameraType().isFirstPerson()&&height>-1.8&&height<1&&mc.player.distanceToSqr(e.getBlockPos().getCenter())<25&&Math.abs(Math.sin(angle*2))>.65){p.pushPose();p.translate(.5,-6.4,.5);p.mulPose(Axis.ZP.rotationDegrees(90));elk.lying();elk.renderToBuffer(p,out.getBuffer(RenderType.entityCutoutNoCull(texture(LiteraryView.models().getBoolean("Scar")?"elk_wounded":"elk"))),light,overlay,0xffffffff);p.popPose();}return;}
            if(kind==LiteraryPropBlock.Kind.MINIATURE){var list=LiteraryView.models().getList("Models",Tag.TAG_COMPOUND);int index=Math.min(2,state.getValue(LiteraryPropBlock.STAGE));if(index>=list.size())return;var model=list.getCompound(index);int[] blocks=model.getIntArray("Blocks");p.pushPose();p.translate(.12,.46,.12);p.scale(.09F,.09F,.09F);for(int i=0;i<Math.min(256,blocks.length);i++){var s=Block.stateById(blocks[i]);if(s.isAir())continue;p.pushPose();p.translate(i%8,i/64,(i/8)%8);mc.getBlockRenderer().renderSingleBlock(s,p,out,light,overlay);p.popPose();}p.pushPose();p.translate(4,1,4);p.scale(.35F,-.35F,-.35F);tiny.renderToBuffer(p,out.getBuffer(RenderType.entityCutoutNoCull(mc.player.getSkin().texture())),light,overlay,0xffffffff);p.popPose();if(model.getBoolean("Behind")){p.pushPose();p.translate(4,1,6);p.scale(.35F,-.35F,-.35F);tiny.renderToBuffer(p,out.getBuffer(RenderType.entityCutoutNoCull(texture("silhouette"))),light,overlay,0xff191719);p.popPose();}p.popPose();return;}
            String text=e.display().getString("Text");if(kind==LiteraryPropBlock.Kind.TRUNK_MARK||kind==LiteraryPropBlock.Kind.PHOTO&&state.getValue(LiteraryPropBlock.STAGE)==3){if(text.isEmpty())text=mc.player.getGameProfile().getName()+", come home";p.pushPose();p.translate(.5,.6,.5);p.mulPose(Axis.YP.rotationDegrees(-state.getValue(LiteraryPropBlock.FACING).toYRot()));p.translate(0,0,.41);p.scale(.009F,-.009F,.009F);mc.font.drawInBatch(text,-mc.font.width(text)/2F,0,0xffd0bca0,false,p.last().pose(),out,net.minecraft.client.gui.Font.DisplayMode.NORMAL,0,light);p.popPose();}
        }
        @Override public boolean shouldRenderOffScreen(LiteraryModelBlockEntity e){return e.getBlockState().is(LiteraryRegistry.PROP.get())&&e.getBlockState().getValue(LiteraryPropBlock.KIND)==LiteraryPropBlock.Kind.FAN;}
        @Override public int getViewDistance(){return 24;}
    }
}
