package io.github.knaitoe.theoldesthouse.gametest;
import io.github.knaitoe.theoldesthouse.TheOldestHouse;
import io.github.knaitoe.theoldesthouse.house.*;
import io.github.knaitoe.theoldesthouse.labyrinth.*;
import java.util.*;
import net.minecraft.core.*;
import net.minecraft.core.component.DataComponents;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.*;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.inventory.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.phys.*;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.event.entity.player.PlayerInteractEvent;
import net.neoforged.neoforge.gametest.*;
@GameTestHolder(TheOldestHouse.MOD_ID)
@PrefixGameTestTemplate(false)
public final class HotelTests {
    private static Fixture arc,custody,plant,blind;
    private static final class Fixture implements AutoCloseable {
        final GameTestHelper h;final ServerLevel l,outside;final BlockPos origin,b,gb;final HouseSavedData oldHouse;final LabyrinthData oldData;final MotherCollection oldMother;final List<ServerPlayer> players=new ArrayList<>();
        Fixture(GameTestHelper h,int x,boolean hotel){this.h=h;l=HouseTestLevel.get(h.getLevel().getServer(),HouseDimensions.INTERIOR);outside=HouseTestLevel.get(l.getServer(),HouseDimensions.OUTSIDE);oldHouse=HouseSavedData.get(l.getServer());oldData=LabyrinthData.get(l.getServer());oldMother=MotherCollection.get(l.getServer());origin=new BlockPos(x,80,x);var house=new HouseSavedData();house.markSpawned(origin);l.getServer().overworld().getDataStorage().set("the_oldest_house",house);l.getServer().overworld().getDataStorage().set("the_oldest_house_labyrinth",new LabyrinthData());l.getServer().overworld().getDataStorage().set("the_oldest_house_mother",new MotherCollection());b=LabyrinthPlaces.base(origin,hotel?LabyrinthPlace.HOTEL:LabyrinthPlace.BLIND_STRETCH);gb=LabyrinthPlaces.base(origin,LabyrinthPlace.HOTEL_GROUNDS);if(hotel){HotelRooms.build(l,b,LabyrinthPlace.HOTEL);HotelRooms.build(outside,gb,LabyrinthPlace.HOTEL_GROUNDS);LabyrinthBuilder.registerDoors(data(),LabyrinthPlace.HOTEL,b);LabyrinthBuilder.registerDoors(data(),LabyrinthPlace.HOTEL_GROUNDS,gb);}else{BlindStretch.build(l,b);LabyrinthBuilder.registerDoors(data(),LabyrinthPlace.BLIND_STRETCH,b);}data().setBuilt(LabyrinthBuilder.VERSION,origin);}
        LabyrinthData data(){return LabyrinthData.get(l.getServer());}CompoundTag own(ServerPlayer p){return HotelVignette.personal(data(),p.getUUID());}
        ServerPlayer player(String name){var p=NativeTestPlayers.survival(h,name);p.teleportTo(l,b.getX()+.5,b.getY(),b.getZ()-3,180,0);p.hasChangedDimension();players.add(p);return p;}
        void at(ServerPlayer p,double x,double y,double z){p.stopRiding();p.moveTo(b.getX()+x,b.getY()+y,b.getZ()+z);p.setDeltaMovement(Vec3.ZERO);}
        void click(ServerPlayer p,BlockPos rel){var at=b.offset(rel);p.stopRiding();p.moveTo(at.getX()+.5,at.getY(),at.getZ()+2.5);NeoForge.EVENT_BUS.post(new PlayerInteractEvent.RightClickBlock(p,InteractionHand.MAIN_HAND,at,new BlockHitResult(at.getCenter(),Direction.SOUTH,at,false)));}
        void read(ServerPlayer p,BlockPos rel){click(p,rel);h.assertTrue(p.containerMenu instanceof HotelVignette.Pages,"hotel surface opens the native private reader");var menu=(HotelVignette.Pages)p.containerMenu;int pages=menu.book().get(DataComponents.WRITTEN_BOOK_CONTENT).pages().size();h.assertTrue(menu.clickMenuButton(p,100+pages-1),"the actual last native page is read");p.closeContainer();}
        void chest(ServerPlayer p){p.closeContainer();p.openMenu(new SimpleMenuProvider((id,inv,who)->ChestMenu.threeRows(id,inv,new SimpleContainer(27)),Component.literal("An ordinary chest")));}
        void torch(ServerPlayer p,BlockPos rel,boolean canceled){var at=b.offset(rel);l.setBlock(at,Blocks.TORCH.defaultBlockState(),3);var event=new net.neoforged.neoforge.event.level.BlockEvent.EntityPlaceEvent(net.neoforged.neoforge.common.util.BlockSnapshot.create(l.dimension(),l,at),Blocks.DARK_OAK_PLANKS.defaultBlockState(),p);if(canceled)event.setCanceled(true);NeoForge.EVENT_BUS.post(event);h.assertTrue(event.isCanceled()==canceled,"native protection admits only the successful 217 torch placement");if(canceled)l.setBlock(at,Blocks.AIR.defaultBlockState(),3);}
        void reload(){var loaded=LabyrinthData.FACTORY.deserializer().apply(data().save(new CompoundTag(),l.registryAccess()),l.registryAccess());l.getServer().overworld().getDataStorage().set("the_oldest_house_labyrinth",loaded);}
        @Override public void close(){for(var p:players)NativeTestPlayers.remove(p);for(var level:List.of(l,outside)){var entities=new ArrayList<Entity>();for(var e:level.getAllEntities())if(e.position().distanceToSqr(level==l?b.getCenter():gb.getCenter())<15000)entities.add(e);entities.forEach(Entity::discard);}l.getServer().overworld().getDataStorage().set("the_oldest_house",oldHouse);l.getServer().overworld().getDataStorage().set("the_oldest_house_labyrinth",oldData);l.getServer().overworld().getDataStorage().set("the_oldest_house_mother",oldMother);}
    }
    @GameTest(template="empty",batch="hotel_arc",timeoutTicks=400)
    public static void actualGuestCanReadOwnClosingAccountWithoutGivingItToAPeer(GameTestHelper h){arc=new Fixture(h,48000,true);var f=arc;var p=f.player("hotel_guest");var peer=f.player("hotel_peer");f.at(peer,35,0,-4);HotelVignette.onArrive(p,LabyrinthPlace.HOTEL);
        var spawn=p.getRespawnPosition();f.at(p,.5,0,-13.5);h.assertTrue(HouseSitting.sit(p,f.b.offset(0,0,-14)),"the remaining native chair takes an actual seated guest");
        h.runAfterDelay(10,()->{h.assertTrue(f.own(p).getBoolean("MealServed")&&!f.own(p).getBoolean("Dinner"),"sitting serves food without silently eating or charging");f.click(p,HotelRooms.MEAL);h.assertTrue(f.own(p).getBoolean("Dinner")&&f.own(p).getInt("Debt")==1,"actually eating opens one tab place");f.read(p,new BlockPos(-6,5,-11));f.at(p,5.5,5,-19.5);h.assertTrue(HotelVignette.rest(p)&&p.isSleeping(),"217 accepts actual native sleep without native respawn registration");});
        h.runAfterDelay(105,()->{h.assertTrue(f.own(p).getBoolean("Rested")&&!p.isSleeping()&&Objects.equals(spawn,p.getRespawnPosition()),"an actual completed rest preserves the native spawn");f.at(p,-21.5,0,-17.5);p.setHealth(12);var drink=new ItemStack(HotelRegistry.DRINK.get());drink.getItem().finishUsingItem(drink,f.l,p);h.assertTrue(drink.isEmpty()&&p.getHealth()==16&&f.own(p).getBoolean("Drank")&&f.own(p).getInt("Debt")==2,"finishing the actual native drink heals and enters the tab");
            f.at(p,20.5,0,-20.5);HotelVignette.photograph(p);h.assertTrue(f.own(p).getBoolean("Photographed")&&p.getInventory().countItem(HotelRegistry.PHOTOGRAPH.get())==1,"standing on the physical parquet creates one photograph");var savedPhoto=ItemStack.parseOptional(p.registryAccess(),f.own(p).getCompound("Original_Photo"));h.assertTrue(savedPhoto.has(DataComponents.PROFILE)&&savedPhoto.get(DataComponents.PROFILE).gameProfile().getId().equals(p.getUUID()),"the actual native profile belongs to the photographed player");h.assertTrue(f.l.getBlockState(f.b.offset(HotelRooms.PHOTO)).is(HotelRegistry.PROP.get())&&f.l.getBlockState(f.b.offset(27,2,-20)).is(Blocks.PLAYER_WALL_HEAD),"the physical native player head occupies the front row inside the two-block print");f.read(p,HotelRooms.LOG);
            p.teleportTo(f.outside,f.gb.getX()+.5,f.gb.getY(),f.gb.getZ()-38,180,0);p.hasChangedDimension();HotelVignette.onArrive(p,LabyrinthPlace.HOTEL_GROUNDS);var at=f.gb.offset(HotelRooms.KEY.below());NeoForge.EVENT_BUS.post(new PlayerInteractEvent.RightClickBlock(p,InteractionHand.MAIN_HAND,at,new BlockHitResult(at.getCenter(),Direction.UP,at,false)));h.assertTrue(f.own(p).getBoolean("MasterKey")&&p.getInventory().countItem(HotelRegistry.MASTER_KEY.get())==1,"the actual maze pedestal gives a finite personally found key");
            p.teleportTo(f.l,f.b.getX()+.5,f.b.getY(),f.b.getZ()-37,180,0);p.hasChangedDimension();p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(HotelRegistry.MASTER_KEY.get()));f.click(p,new BlockPos(0,0,-39));h.assertTrue(f.l.getBlockState(f.b.offset(0,0,-39)).getValue(DoorBlock.OPEN),"the native master key opens the physical service door");f.at(p,4.5,-4,-56.5);
        });
        h.runAfterDelay(120,()->{h.assertTrue(f.data().state(HotelVignette.STATE).getBoolean("PlantFound"),"only actual boiler-room presence starts the plant");HotelVignette.maintain(p,false);h.assertTrue(f.own(p).getBoolean("Maintained"),"the real reachable valve records maintenance");f.at(p,2.5,0,-2.5);p.getInventory().add(new ItemStack(Items.DIAMOND,3));f.chest(p);f.chest(p);h.assertTrue(f.own(p).getInt("Debt")==0&&f.own(p).getList("LostProperty",Tag.TAG_COMPOUND).size()==2,"two actual native chest openings settle two places into recovery custody");p.closeContainer();h.assertTrue(HotelVignette.ready(f.own(p))&&!WitnessAccount.has(f.data(),p.getUUID(),WitnessAccount.Story.HOTEL),"all experiences still require the guest's final account reading");f.read(p,HotelRooms.DESK);h.assertTrue(WitnessAccount.has(f.data(),p.getUUID(),WitnessAccount.Story.HOTEL)&&!WitnessAccount.has(f.data(),peer.getUUID(),WitnessAccount.Story.HOTEL),"the last actual native page credits only the guest");
            var original=ItemStack.parseOptional(p.registryAccess(),f.own(p).getCompound("Original_Account"));f.at(peer,3.5,0,-2);HotelVignette.readCollected(peer,original);var menu=(HotelVignette.Pages)peer.containerMenu;h.assertTrue(menu.clickMenuButton(peer,101)&&!f.own(peer).getBoolean("Read_Account")&&!WitnessAccount.has(f.data(),peer.getUUID(),WitnessAccount.Story.HOTEL),"a borrowed closing account remains readable without assigning its reading or credit");peer.setGameMode(GameType.SPECTATOR);h.assertTrue(!HotelVignette.inside(peer,LabyrinthPlace.HOTEL),"native observer mode excludes participation");f.reload();h.assertTrue(WitnessAccount.has(f.data(),p.getUUID(),WitnessAccount.Story.HOTEL)&&f.own(p).getBoolean("ClosedAccount"),"the actual account and Witness record survive native SavedData reload");h.succeed();});
    }
    @GameTest(template="empty",batch="hotel_property",timeoutTicks=300)
    public static void repeatRestAndTabRecoverExactNamedEnchantedStacksWithoutRefill(GameTestHelper h){custody=new Fixture(h,48500,true);var f=custody;var p=f.player("hotel_property");var peer=f.player("hotel_other");f.at(peer,35,0,-5);f.at(p,5.5,5,-19.5);var original=new ItemStack(Items.DIAMOND_PICKAXE);original.set(DataComponents.CUSTOM_NAME,Component.literal("The tool I kept"));original.setDamageValue(83);original.enchant(p.registryAccess().lookupOrThrow(net.minecraft.core.registries.Registries.ENCHANTMENT).getOrThrow(net.minecraft.world.item.enchantment.Enchantments.UNBREAKING),2);p.getInventory().setItem(8,original.copy());f.torch(p,new BlockPos(8,5,-15),false);f.torch(p,new BlockPos(8,5,-15),false);f.torch(p,new BlockPos(8,5,-17),false);f.torch(p,new BlockPos(8,5,-19),true);f.at(peer,6.5,5,-19.5);f.torch(peer,new BlockPos(8,5,-17),false);f.at(peer,35,0,-5);h.assertTrue(HotelVignette.rest(p),"first rest begins at the actual bed");
        h.runAfterDelay(95,()->{h.assertTrue(f.own(p).getBoolean("Rested")&&p.getInventory().items.stream().anyMatch(s->ItemStack.matches(s,original)),"sorting keeps all native components: rest="+f.own(p)+", sleeping="+p.isSleeping()+", inventory="+p.getInventory().items);h.assertTrue(p.getInventory().countItem(Items.TORCH)==1&&f.l.getBlockState(f.b.offset(8,5,-15)).isAir()&&f.l.getBlockState(f.b.offset(8,5,-17)).is(Blocks.TORCH),"housekeeping returns one original light, excludes canceled placement and leaves a peer's replacement");for(int i=0;i<p.getInventory().items.size();i++)if(p.getInventory().items.get(i).is(Items.TORCH))p.getInventory().items.set(i,ItemStack.EMPTY);h.assertTrue(HotelVignette.rest(p),"a later deliberate rest stores pockets");});
        h.runAfterDelay(190,()->{h.assertTrue(p.getInventory().items.stream().allMatch(ItemStack::isEmpty),"a completed second rest empties only main pockets");h.assertTrue(f.own(p).getList("Drawers",Tag.TAG_COMPOUND).size()==1&&f.own(peer).getList("Drawers",Tag.TAG_COMPOUND).isEmpty(),"custody belongs only to this guest");var saved=f.own(p).getCompound("Original_Rules").copy();f.reload();HotelVignette.openProperty(p,true);var menu=(ChestMenu)p.containerMenu;h.assertTrue(ItemStack.matches(menu.getContainer().getItem(0),original),"native reload and menu keep the exact enchanted/damaged original");menu.clicked(0,0,ClickType.QUICK_MOVE,p);p.closeContainer();h.assertTrue(p.getInventory().items.stream().anyMatch(s->ItemStack.matches(s,original))&&f.own(p).getList("Drawers",Tag.TAG_COMPOUND).isEmpty(),"native shift-click transfers custody once, without duplication");HotelVignette.openProperty(p,true);h.assertTrue(((ChestMenu)p.containerMenu).getContainer().isEmpty(),"opening again does not replenish the drawer");p.closeContainer();
            var own=f.own(p);own.putInt("Debt",1);HotelVignette.save(f.data(),p.getUUID(),own);f.chest(p);h.assertTrue(f.own(p).getInt("Debt")==0&&p.getInventory().items.stream().allMatch(ItemStack::isEmpty),"a real chest collects exactly one stack unit into saved lost property");p.closeContainer();HotelVignette.openProperty(p,false);menu=(ChestMenu)p.containerMenu;h.assertTrue(ItemStack.matches(menu.getContainer().getItem(0),original),"lost property retains the same complete components");menu.clicked(0,0,ClickType.QUICK_MOVE,p);p.closeContainer();f.reload();h.assertTrue(f.own(p).getList("LostProperty",Tag.TAG_COMPOUND).isEmpty()&&p.getInventory().items.stream().anyMatch(s->ItemStack.matches(s,original)),"recovery, close and reload do not duplicate the original");h.succeed();});
    }
    @GameTest(template="empty",batch="hotel_plant",timeoutTicks=100)
    public static void boilerStartsOnDiscoveryBlowsOnceAndRestartsOnlyItsHotel(GameTestHelper h){plant=new Fixture(h,49000,true);var f=plant;var p=f.player("hotel_engineer");h.assertTrue(!f.data().state(HotelVignette.STATE).getBoolean("PlantFound"),"the empty hotel has no running boiler");f.at(p,4.5,-4,-56.5);
        h.runAfterDelay(5,()->{var world=f.data().state(HotelVignette.STATE);h.assertTrue(world.getBoolean("PlantFound"),"physical discovery starts the gauge");long start=world.getLong("VentedAt");h.assertTrue(HotelVignette.pressure(world,start+48000)==2,"pressure advances by actual in-game days");var bed=f.l.getBlockState(f.b.offset(HotelRooms.BED));var roomClock=SceneClock.time(0,1,12345);HotelVignette.plantTick(f.l,f.b,start+72000);HotelVignette.plantTick(f.l,f.b,start+80000);h.assertTrue(f.data().state(HotelVignette.STATE).getBoolean("Cold")&&f.data().state(HotelVignette.STATE).getInt("Blasts")==1,"neglect blows once and remains cold");h.assertTrue(!f.l.getBlockState(f.b.offset(HotelRooms.FIRE)).getValue(CampfireBlock.LIT)&&f.l.getBlockState(f.b.offset(HotelRooms.BED)).equals(bed)&&SceneClock.time(0,1,12345)==roomClock,"the hotel fire goes out without breaking the bed or changing world time");f.at(p,5.5,5,-19.5);h.assertTrue(!HotelVignette.rest(p),"cold 217 refuses the real rest");f.at(p,6.5,-4,-56.5);HotelVignette.maintain(p,true);h.assertTrue(!f.data().state(HotelVignette.STATE).getBoolean("Cold")&&f.l.getBlockState(f.b.offset(HotelRooms.FIRE)).getValue(CampfireBlock.LIT),"the physical restart switch restores only the hotel plant");f.at(p,5.5,5,-19.5);h.assertTrue(HotelVignette.rest(p),"restart restores the hotel's made bed");h.succeed();});
    }
    @GameTest(template="empty",batch="hotel_blind",timeoutTicks=100)
    public static void blindTurnsHaveARealRetraceablePathAndIndependentHonestSoundSources(GameTestHelper h){blind=new Fixture(h,49500,false);var f=blind;var p=f.player("blind_walker");int stage=0;BlockPos previous=new BlockPos(0,0,-3);
        for(var turn:BlindStretch.TURNS){int dx=Integer.signum(turn.getX()-previous.getX()),dz=Integer.signum(turn.getZ()-previous.getZ());var at=previous;while(!at.equals(turn)){at=at.offset(dx,0,dz);h.assertTrue(f.l.noCollision(null,new AABB(f.b.getX()+at.getX()+.2,f.b.getY()+.01,f.b.getZ()+at.getZ()+.2,f.b.getX()+at.getX()+.8,f.b.getY()+1.8,f.b.getZ()+at.getZ()+.8)),"every real blind-route cell clears a native player body");h.assertTrue(!f.l.getBlockState(f.b.offset(at).below()).isAir(),"each blind turn has a physical supported return floor");}stage=BlindStretch.advance(stage,f.b,f.b.offset(turn).getCenter());previous=turn;}
        h.assertTrue(stage==6&&!BlindStretch.lies(0)&&!BlindStretch.lies(1)&&BlindStretch.lies(2),"arrows begin lying after the two actual first turns");h.assertTrue(LabyrinthLoops.LONG_HALLWAY_TICKS==6600&&!LabyrinthPlace.BLIND_STRETCH.isVignette()&&WitnessAccount.Story.of("blind_stretch")==null,"the timed hall and Witness pool remain independent");f.at(p,.5,0,-9.5);
        h.runAfterDelay(25,()->{var own=f.data().stateEntry(BlindStretch.STATE,p.getUUID().toString());h.assertTrue(own.getInt("Turn")>=1,"present native movement records the actual turn, without elapsed-time shortcuts");f.reload();h.assertTrue(f.data().stateEntry(BlindStretch.STATE,p.getUUID().toString()).getInt("Turn")>=1,"native save reload preserves the blind route");h.succeed();});
    }
    @GameTest(template="empty",batch="hotel_routes",timeoutTicks=100)
    public static void appendedHotelHasRealDoorApproachesStairsFloorDropAndReachableMaze(GameTestHelper h){var f=new Fixture(h,49700,true);try{
        for(var point:List.of(new BlockPos(0,0,-3),new BlockPos(0,0,-5),new BlockPos(-14,0,-6),new BlockPos(-14,2,-9),new BlockPos(-14,5,-13),new BlockPos(-10,5,-13),new BlockPos(0,5,-7),new BlockPos(-14,0,-35),new BlockPos(0,0,-37),new BlockPos(7,-4,-47),new BlockPos(8,-4,-50),new BlockPos(4,-4,-56),new BlockPos(-17,0,-44),new BlockPos(14,0,-17),new BlockPos(18,0,-39),new BlockPos(18,0,-47),new BlockPos(18,0,-50),new BlockPos(24,0,-50))){var at=f.b.offset(point);h.assertTrue(f.l.noCollision(null,new AABB(at.getX()+.2,at.getY()+.08,at.getZ()+.2,at.getX()+.8,at.getY()+1.8,at.getZ()+.8)),"hotel's native door/stair approach clears a body at "+point);}
        h.assertTrue(f.l.getBlockState(f.b.offset(15,0,-61)).is(Blocks.CHEST)&&f.l.getBlockState(f.b.offset(14,1,-48)).is(Blocks.GLASS)&&f.l.getBlockState(f.b.offset(-10,-3,-55)).is(Blocks.STONE_BRICKS)&&f.l.getBlockState(f.b.offset(-14,5,-14)).is(Blocks.DARK_OAK_FENCE),"the native hotel has usable linen chests, backed office glass, masonry plant and supported stair rails");h.assertTrue(LabyrinthDealer.vignettesAvailable(f.data()).contains(LabyrinthPlace.HOTEL),"the recurring hotel remains an available property-recovery anchor");h.assertTrue(f.l.getBlockState(f.b.offset(HotelRooms.PATCH)).is(HotelRegistry.PROP.get())&&f.l.getBlockState(f.b.offset(HotelRooms.PATCH).below()).isAir(),"the upstairs patch lies physically above the dining table");
        var todo=new ArrayDeque<BlockPos>();var seen=new HashSet<BlockPos>();var start=new BlockPos(0,0,-26);todo.add(start);seen.add(start);while(!todo.isEmpty()){var at=todo.remove();for(var side:Direction.Plane.HORIZONTAL){var next=at.relative(side);if(Math.abs(next.getX())>15||next.getZ()<-56||next.getZ()>-25||!seen.add(next))continue;var abs=f.gb.offset(next);if(f.outside.noCollision(null,new AABB(abs.getX()+.2,abs.getY()+.01,abs.getZ()+.2,abs.getX()+.8,abs.getY()+1.8,abs.getZ()+.8)))todo.add(next);}}h.assertTrue(seen.contains(HotelRooms.KEY),"the actual native hedge maze reaches its master-key center");
        for(int y:new int[]{70,80,200,300}){var origin=new BlockPos(0,y,0);for(var place:LabyrinthPlace.values())if(place.slot()>=0)h.assertTrue(LabyrinthPlaces.base(origin,place)!=null,"appending rooms preserves a valid slot at each supported manor height");}h.assertTrue(NovelRooms.outside(LabyrinthPlace.HOTEL_GROUNDS)&&SceneClock.time(8,0,6000)==18000,"hotel grounds have real outside sky and their own spatial blizzard night");h.assertTrue(WitnessAccount.Story.values().length==20&&WitnessAccount.REQUIRED==15,"one complete hotel account adds one source and derives fifteen of twenty");h.succeed();}finally{f.close();}}
    @GameTest(template="empty",batch="hotel_history",timeoutTicks=100)
    public static void cemeteryRecordsActualNamedPetDeathAndCanceledEventsInventNothing(GameTestHelper h){var f=new Fixture(h,49900,true);try{var p=f.player("hotel_history");var wolf=EntityType.WOLF.create(f.l);h.assertTrue(wolf!=null,"the native tame wolf exists");wolf.setTame(true,false);wolf.setOwnerUUID(p.getUUID());wolf.setCustomName(Component.literal("Moss"));wolf.moveTo(f.b.getX()+4,f.b.getY(),f.b.getZ()-4);f.l.addFreshEntity(wolf);h.assertTrue(wolf.hurt(f.l.damageSources().genericKill(),1000),"an actual native death occurs");h.assertTrue(f.own(p).getList("LostPets",Tag.TAG_COMPOUND).size()==1&&f.own(p).getList("LostPets",Tag.TAG_COMPOUND).getCompound(0).getString("Name").equals("Moss"),"the ledger retains the actual companion UUID and name");var prior=f.own(p).copy();var event=new net.neoforged.neoforge.event.entity.living.LivingDeathEvent(p,f.l.damageSources().generic());event.setCanceled(true);NeoForge.EVENT_BUS.post(event);h.assertTrue(f.own(p).equals(prior),"a canceled death does not invent a hotel tale or lost companion");f.reload();h.assertTrue(f.own(p).getList("LostPets",Tag.TAG_COMPOUND).getCompound(0).getUUID("Entity").equals(wolf.getUUID()),"the actual pet identity survives native save reload");h.succeed();}finally{f.close();}}
    @AfterBatch(batch="hotel_arc") public static void closeArc(ServerLevel l){if(arc!=null){arc.close();arc=null;}}
    @AfterBatch(batch="hotel_property") public static void closeCustody(ServerLevel l){if(custody!=null){custody.close();custody=null;}}
    @AfterBatch(batch="hotel_plant") public static void closePlant(ServerLevel l){if(plant!=null){plant.close();plant=null;}}
    @AfterBatch(batch="hotel_blind") public static void closeBlind(ServerLevel l){if(blind!=null){blind.close();blind=null;}}
}
