package io.github.knaitoe.theoldesthouse.gametest;
import io.github.knaitoe.theoldesthouse.TheOldestHouse;
import io.github.knaitoe.theoldesthouse.house.*;
import io.github.knaitoe.theoldesthouse.labyrinth.*;
import java.util.*;
import net.minecraft.commands.arguments.EntityAnchorArgument;
import net.minecraft.core.*;
import net.minecraft.core.component.DataComponents;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.server.level.*;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.entity.*;
import net.minecraft.world.phys.*;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.event.entity.player.PlayerInteractEvent;
import net.neoforged.neoforge.event.level.BlockEvent;
import net.neoforged.neoforge.gametest.*;
/** Native interactions, present-time playback, saved originals and private projection boundaries. */
@GameTestHolder(TheOldestHouse.MOD_ID+"_literary") @PrefixGameTestTemplate(false)
public final class LiteraryTests {
    private static Fixture active;
    private static final class Fixture implements AutoCloseable {
        final GameTestHelper h;final ServerLevel in,out;final BlockPos origin;final HouseSavedData oldHouse;final LabyrinthData oldData;final MotherCollection oldMother;final LiteraryCopies oldCopies;final List<ServerPlayer> players=new ArrayList<>();final Set<LabyrinthPlace> built=new HashSet<>();final long oldDay;final List<Entity> extras=new ArrayList<>();
        Fixture(GameTestHelper h){this.h=h;oldDay=h.getLevel().getServer().overworld().getDayTime();in=HouseTestLevel.get(h.getLevel().getServer(),HouseDimensions.INTERIOR);out=HouseTestLevel.get(in.getServer(),HouseDimensions.OUTSIDE);oldHouse=HouseSavedData.get(in.getServer());oldData=LabyrinthData.get(in.getServer());oldMother=MotherCollection.get(in.getServer());oldCopies=LiteraryCopies.get(in.getServer());origin=new BlockPos(57000,80,57000);var house=new HouseSavedData();house.markSpawned(origin);var store=in.getServer().overworld().getDataStorage();store.set("the_oldest_house",house);store.set("the_oldest_house_labyrinth",new LabyrinthData());store.set("the_oldest_house_mother",new MotherCollection());store.set("the_oldest_house_literary_copies",new LiteraryCopies());data().setBuilt(LabyrinthBuilder.VERSION,origin);active=this;}
        LabyrinthData data(){return LabyrinthData.get(in.getServer());}ServerLevel level(LabyrinthPlace p){return NovelRooms.outside(p)?out:in;}BlockPos base(LabyrinthPlace p){return LabyrinthPlaces.base(origin,p);}
        void build(LabyrinthPlace p){if(built.add(p)){LiteraryRooms.build(level(p),base(p),p);LabyrinthBuilder.registerDoors(data(),p,base(p));}}
        ServerPlayer player(String name,LabyrinthPlace place){build(place);var p=NativeTestPlayers.survival(h,name);players.add(p);arrive(p,place);return p;}
        void arrive(ServerPlayer p,LabyrinthPlace place){build(place);var b=base(place);p.stopRiding();p.teleportTo(level(place),b.getX()+.5,b.getY(),b.getZ()-3,180,0);p.hasChangedDimension();p.setNoGravity(true);p.setDeltaMovement(Vec3.ZERO);LiteraryVignettes.onArrive(p,place);}
        void at(ServerPlayer p,LabyrinthPlace place,double x,double y,double z){var b=LiteraryVignettes.base(p,place);p.stopRiding();p.moveTo(b.getX()+x,b.getY()+y,b.getZ()+z);p.setDeltaMovement(Vec3.ZERO);}
        void look(ServerPlayer p,BlockPos at){p.lookAt(EntityAnchorArgument.Anchor.EYES,at.getCenter());}
        CompoundTag own(ServerPlayer p,LabyrinthPlace place){return LiteraryVignettes.personal(data(),p.getUUID(),place);}
        void click(ServerPlayer p,LabyrinthPlace place,BlockPos rel){var b=LiteraryVignettes.base(p,place);var at=b.offset(rel);p.moveTo(at.getX()+.5,at.getY(),at.getZ()+2.5);p.setDeltaMovement(Vec3.ZERO);look(p,at);NeoForge.EVENT_BUS.post(new PlayerInteractEvent.RightClickBlock(p,InteractionHand.MAIN_HAND,at,new BlockHitResult(at.getCenter(),Direction.SOUTH,at,false)));}
        void read(ServerPlayer p,LabyrinthPlace place,BlockPos rel){click(p,place,rel);h.assertTrue(p.containerMenu instanceof LiteraryVignettes.Pages,"actual scene surface opens its native private paper: "+place);var menu=(LiteraryVignettes.Pages)p.containerMenu;var book=menu.original().get(DataComponents.WRITTEN_BOOK_CONTENT);h.assertTrue(menu.clickMenuButton(p,100+book.pages().size()-1),"the actual final page is read");p.closeContainer();}
        void source(ServerPlayer p,LabyrinthPlace place){read(p,place,LiteraryRooms.source(place));}
        void reload(){var l=in;var store=l.getServer().overworld().getDataStorage();store.set("the_oldest_house_labyrinth",LabyrinthData.FACTORY.deserializer().apply(data().save(new CompoundTag(),l.registryAccess()),l.registryAccess()));}
        @Override public void close(){LiteraryVignettes.clearAll();for(var p:players){for(var place:List.of(LabyrinthPlace.FAMILY_COPY,LabyrinthPlace.OLD_CABIN)){var b=LiteraryCopies.base(in.getServer(),p.getUUID(),place);if(b!=null)for(var entity:out.getEntitiesOfClass(Entity.class,new AABB(b.getX()-36,b.getY()-20,b.getZ()-100,b.getX()+37,b.getY()+36,b.getZ()+6)))entity.discard();}NativeTestPlayers.remove(p);}extras.forEach(Entity::discard);in.getServer().overworld().setDayTime(oldDay);for(var place:built){var b=base(place);var r=place.room();for(var e:level(place).getEntitiesOfClass(Entity.class,new AABB(b.getX()+r.minX()-2,b.getY()+r.minY()-2,b.getZ()+r.minZ()-2,b.getX()+r.maxX()+3,b.getY()+r.maxY()+3,b.getZ()+5)))e.discard();}var s=in.getServer().overworld().getDataStorage();s.set("the_oldest_house",oldHouse);s.set("the_oldest_house_labyrinth",oldData);s.set("the_oldest_house_mother",oldMother);s.set("the_oldest_house_literary_copies",oldCopies);}
    }
    private static void close(){if(active!=null){active.close();active=null;}}
    @GameTest(template="empty",batch="literary_papers",timeoutTicks=300)
    public static void discoveryOriginalsAreFiniteReaderOwnedAndImmutableAcrossReload(GameTestHelper h){var f=new Fixture(h);var place=LabyrinthPlace.HILL_NURSERY;var p=f.player("literary_reader",place);var peer=f.player("literary_peer",place);f.at(peer,place,0,0,-6);f.source(p,place);var snapshot=f.own(p,place).getCompound("Original_Source").copy();h.assertTrue(!snapshot.isEmpty(),"opening the note persists its exact original instead of overwriting it with pre-menu state");f.click(p,place,LiteraryRooms.source(place));var menu=(LiteraryVignettes.Pages)p.containerMenu;h.assertTrue(menu.clickMenuButton(p,3)&&!menu.clickMenuButton(p,3),"the native paper may be taken once");p.closeContainer();f.reload();f.source(p,place);h.assertTrue(snapshot.equals(f.own(p,place).getCompound("Original_Source")),"native SavedData reload and rereading preserve the original bytes");h.assertTrue(!f.own(peer,place).getBoolean("Read_Source")&&!f.own(peer,place).getBoolean("Taken_Source"),"one explorer's source is not another's discovery");peer.setGameMode(GameType.SPECTATOR);h.assertTrue(!LiteraryVignettes.inside(peer,place),"native observers have no participation authority");h.succeed();}
    @AfterBatch(batch="literary_papers") public static void papersDone(ServerLevel l){close();}
    @GameTest(template="empty",batch="literary_hill",timeoutTicks=200)
    public static void actualColdDoorNameAndCountedKnocksEarnOnlyTheReadersAccount(GameTestHelper h){var f=new Fixture(h);var place=LabyrinthPlace.HILL_NURSERY;var p=f.player("hill_reader",place);f.source(p,place);f.at(p,place,-9.5,0,-17);f.look(p,f.base(place).offset(LiteraryRooms.HILL_WALL));h.runAfterDelay(10,()->{h.assertTrue(f.own(p,place).getBoolean("ColdDoor")&&f.own(p,place).getBoolean("NameSeen"),"native doorway presence and line of sight are required");f.at(p,place,-9.5,-4,-34);for(int i=0;i<3;i++)NeoForge.EVENT_BUS.post(new PlayerInteractEvent.LeftClickBlock(p,f.base(place).offset(LiteraryRooms.HILL_KNOCK),Direction.SOUTH,PlayerInteractEvent.LeftClickBlock.Action.START));});h.runAfterDelay(50,()->{h.assertTrue(f.own(p,place).getInt("Knocks")==3&&f.own(p,place).getInt("Echoes")==3&&f.own(p,place).getBoolean("Ready"),"each actual knock returns once at its cellar source");f.read(p,place,LiteraryRooms.ending(place));h.assertTrue(WitnessAccount.has(f.data(),p.getUUID(),WitnessAccount.Story.HILL_NURSERY),"reading the own ending grants one eligible source");h.succeed();});}
    @AfterBatch(batch="literary_hill") public static void hillDone(ServerLevel l){close();}
    @GameTest(template="empty",batch="literary_coffin",timeoutTicks=230)
    public static void nativeCoffinChoiceRequiresAReturnAndKeepsTheSameWoman(GameTestHelper h){var f=new Fixture(h);var place=LabyrinthPlace.USHER;var p=f.player("coffin_reader",place);f.source(p,place);h.runAfterDelay(10,()->{var world=LiteraryVignettes.shared(f.data(),place);h.assertTrue(world.hasUUID("Woman"),"the living native body is present before the decision");p.setShiftKeyDown(true);f.click(p,place,LiteraryRooms.COFFIN);p.setShiftKeyDown(false);h.assertTrue(f.own(p,place).getBoolean("LidClosed")&&!f.own(p,place).getBoolean("Ready"),"closing the physical lid grants no ending by itself");f.arrive(p,place);f.at(p,place,2,-3,-29);});h.runAfterDelay(150,()->{var world=LiteraryVignettes.shared(f.data(),place);h.assertTrue(world.getInt("Cracks")==1&&f.own(p,place).getBoolean("Ready"),"the next native visit brings a local crack and an earned consequence");h.assertTrue(f.in.getEntity(world.getUUID("Woman")) instanceof LiteraryActor,"the same woman's native UUID survives the return");f.read(p,place,LiteraryRooms.ending(place));h.succeed();});}
    @AfterBatch(batch="literary_coffin") public static void coffinDone(ServerLevel l){close();}
    @GameTest(template="empty",batch="literary_cylinders",timeoutTicks=750)
    public static void threeOwnedRecordsMustActuallyPlayThroughTheirNativeSongLengths(GameTestHelper h){var f=new Fixture(h);var place=LabyrinthPlace.CRIMSON_HALL;var p=f.player("cylinder_reader",place);f.source(p,place);int cylinder=0;for(var rel:List.of(new BlockPos(-12,0,-35),new BlockPos(12,0,-35),new BlockPos(0,7,-39))){f.click(p,place,rel);Item expected=new Item[]{LiteraryRegistry.CYLINDER_ONE.get(),LiteraryRegistry.CYLINDER_TWO.get(),LiteraryRegistry.CYLINDER_THREE.get()}[cylinder];h.assertTrue(p.getInventory().countItem(expected)==1,"actual cylinder surface "+cylinder+" supplies its finite record");cylinder++;}p.closeContainer();var at=f.base(place).offset(-3,0,-27);f.in.setBlock(at,Blocks.SNOW.defaultBlockState(),3);p.getInventory().selected=8;p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(Items.IRON_SHOVEL));var event=new BlockEvent.BreakEvent(f.in,at,f.in.getBlockState(at),p);NeoForge.EVENT_BUS.post(event);h.assertTrue(!event.isCanceled(),"the native shovel exception admits snow clearing");f.in.setBlock(at,Blocks.AIR.defaultBlockState(),3);f.at(p,place,2,0,-30);var box=(JukeboxBlockEntity)f.in.getBlockEntity(f.base(place).offset(0,0,-30));Item[] records={LiteraryRegistry.CYLINDER_ONE.get(),LiteraryRegistry.CYLINDER_TWO.get(),LiteraryRegistry.CYLINDER_THREE.get()};
        for(int n=0;n<3;n++){final int index=n;h.runAfterDelay(10+n*210,()->{var disc=p.getInventory().items.stream().filter(s->s.is(records[index])).findFirst().orElseThrow().copy();box.setItem(0,disc);h.assertTrue(box.getSongPlayer().isPlaying(),"the owned cylinder starts native audio");});}
        h.runAfterDelay(25,()->h.assertTrue(f.own(p,place).getInt("HeardCylinders")==0,"a few present ticks cannot complete the first voice"));h.runAfterDelay(635,()->{h.assertTrue(f.own(p,place).getInt("HeardCylinders")==7&&f.own(p,place).getBoolean("Ready"),"all three actual native song lengths and the shovel action resolve the hall");f.read(p,place,LiteraryRooms.ending(place));h.succeed();});}
    @AfterBatch(batch="literary_cylinders") public static void cylindersDone(ServerLevel l){close();}
    @GameTest(template="empty",batch="literary_mapping",timeoutTicks=200)
    public static void theRealLowPassageChoiceAndReturnObserveTheBrothersConsequence(GameTestHelper h){var f=new Fixture(h);var place=LabyrinthPlace.MAPPING_INTERIOR;var p=f.player("mapping_reader",place);f.source(p,place);f.at(p,place,-6,0,-26);f.look(p,f.base(place).offset(-9,1,-26));h.runAfterDelay(10,()->{h.assertTrue(f.own(p,place).getBoolean("SilhouetteSeen"),"the native silhouette must actually be seen");f.at(p,place,0,-5,-42);});h.runAfterDelay(20,()->{h.assertTrue(f.own(p,place).getBoolean("BeyondRoof")&&p.getForcedPose()==Pose.SWIMMING,"the player actually crawls beyond the manufactured roof");f.click(p,place,LiteraryRooms.PILE);h.assertTrue(f.own(p,place).getBoolean("PileChosen")&&p.getInventory().countItem(LiteraryRegistry.PHOTOGRAPH.get())==1,"taking the actual pile creates one owned photograph");f.arrive(p,place);f.at(p,place,3,0,-31);f.look(p,f.base(place).offset(6,1,-32));});h.runAfterDelay(40,()->{h.assertTrue(f.own(p,place).getBoolean("Ready")&&!f.own(p,place).getBoolean("PileBroken"),"returning to see the fading brother resolves this player's kept-things choice");f.read(p,place,LiteraryRooms.ending(place));h.succeed();});}
    @AfterBatch(batch="literary_mapping") public static void mappingDone(ServerLevel l){close();}
    @GameTest(template="empty",batch="literary_fan",timeoutTicks=250)
    public static void actualPlacedReachRepairBladeStrikeAndTwoReturnsExposeTheTooth(GameTestHelper h){var f=new Fixture(h);var place=LabyrinthPlace.ELK_FAN;var p=f.player("fan_reader",place);f.source(p,place);var at=f.base(place).offset(1,0,-16);f.in.setBlock(at,Blocks.COBBLESTONE.defaultBlockState(),3);var event=new BlockEvent.EntityPlaceEvent(net.neoforged.neoforge.common.util.BlockSnapshot.create(f.in.dimension(),f.in,at),Blocks.AIR.defaultBlockState(),p);NeoForge.EVENT_BUS.post(event);h.assertTrue(!event.isCanceled()&&f.own(p,place).getBoolean("BuiltReach"),"a genuine final placed block is recorded even with an empty hand");f.click(p,place,LiteraryRooms.FAN);f.at(p,place,0,5,-17);f.look(p,f.base(place).offset(0,0,-17));h.runAfterDelay(90,()->{h.assertTrue(f.own(p,place).getBoolean("Repaired")&&f.own(p,place).getBoolean("BladeStrike")&&f.own(p,place).getBoolean("ElkThroughFan"),"repair, the physical fan sightline and native blade strike all belong to visit one");f.arrive(p,place);f.at(p,place,0,0,-15);f.look(p,f.base(place).offset(0,0,-17));});h.runAfterDelay(110,()->{h.assertTrue(f.own(p,place).getBoolean("TapeSeen"),"the next actual visit exposes the taped shape");f.arrive(p,place);f.at(p,place,0,0,-15);});h.runAfterDelay(130,()->{h.assertTrue(f.own(p,place).getBoolean("Ready"),"a third visit reaches the peeled outline");f.read(p,place,LiteraryRooms.ending(place));h.assertTrue(p.getInventory().countItem(LiteraryRegistry.TOOTH.get())==1,"the owned final reading gives the tooth once");f.read(p,place,LiteraryRooms.ending(place));h.assertTrue(p.getInventory().countItem(LiteraryRegistry.TOOTH.get())==1,"rereading cannot replenish it");h.succeed();});}
    @AfterBatch(batch="literary_fan") public static void fanDone(ServerLevel l){close();}
    @GameTest(template="empty",batch="literary_food",timeoutTicks=100)
    public static void frozenFoodStaysCarriedAndTheSameNightMealCannotBeCountedTwice(GameTestHelper h){var f=new Fixture(h);var place=LabyrinthPlace.HOLY_RABBIT;var p=f.player("hollow_reader",place);f.at(p,place,1,0,-22);var bread=new ItemStack(Items.BREAD,4);p.setItemInHand(InteractionHand.MAIN_HAND,bread);var eating=new net.neoforged.neoforge.event.entity.living.LivingEntityUseItemEvent.Start(p,bread,32);NeoForge.EVENT_BUS.post(eating);h.assertTrue(eating.isCanceled()&&bread.getCount()==4,"cold blocks eating without confiscating the native carried food");h.runAfterDelay(10,()->{var own=f.own(p,place);var token=UUID.randomUUID();own.putUUID("MealToken",token);LiteraryVignettes.save(f.data(),p.getUUID(),place,own);var meal=LiteraryVignettes.mark(p,place,"Meal1",new ItemStack(LiteraryRegistry.MEAL.get()));net.minecraft.world.item.component.CustomData.update(DataComponents.CUSTOM_DATA,meal,t->{t.putInt("Night",own.getInt("Night"));t.putUUID("MealToken",token);});var replay=meal.copy();meal.getItem().finishUsingItem(meal,f.out,p);LiteraryVignettes.ate(p,replay);h.assertTrue(f.own(p,place).getInt("Meals")==1&&p.getFoodData().getFoodLevel()>6,"actual native eating raises hunger and consumes this night's permission once");h.succeed();});}
    @AfterBatch(batch="literary_food") public static void foodDone(ServerLevel l){close();}
    @GameTest(template="empty",batch="literary_frozen",timeoutTicks=100)
    public static void frozenNativeMachineryAndFarmKeepTheirMeshShapeAndNoPower(GameTestHelper h){var f=new Fixture(h);var place=LabyrinthPlace.MAPPING_INTERIOR;f.build(place);var at=f.base(place).offset(18,0,-10);var original=Blocks.PISTON.defaultBlockState().setValue(net.minecraft.world.level.block.state.properties.BlockStateProperties.FACING,Direction.UP);f.out.setBlock(at,LiteraryRegistry.FROZEN.get().defaultBlockState(),3);var be=(LiteraryModelBlockEntity)f.out.getBlockEntity(at);var t=new CompoundTag();t.put("FrozenState",NbtUtils.writeBlockState(original));be.display(t);h.assertTrue(LiteraryFrozenBlock.original(f.out,at).equals(original)&&!f.out.getBlockState(at).isRandomlyTicking()&&!f.out.getBlockState(at).isSignalSource(),"the native captured piston retains its exact visual state without native activity");h.assertTrue(!f.out.getBlockState(at).getCollisionShape(f.out,at).isEmpty(),"frozen mechanisms retain physical collision");h.assertTrue(LiteraryFrozenBlock.freezes(Blocks.WHEAT.defaultBlockState())&&LiteraryFrozenBlock.freezes(Blocks.FARMLAND.defaultBlockState()),"both crops and their supporting farmland use the inactive native projection");var saved=be.saveWithFullMetadata(f.out.registryAccess());be.loadWithComponents(saved,f.out.registryAccess());h.assertTrue(LiteraryFrozenBlock.original(f.out,at).equals(original),"the original mesh state survives native block-entity serialization");h.succeed();}
    @AfterBatch(batch="literary_frozen") public static void frozenDone(ServerLevel l){close();}
    @GameTest(template="empty",batch="literary_registry",timeoutTicks=100)
    public static void eligibleSourcesAndOneOptionalClosureLeaveTheWitnessReachable(GameTestHelper h){var data=new LabyrinthData();var player=UUID.randomUUID();h.assertTrue(WitnessAccount.Story.values().length==43&&WitnessAccount.REQUIRED==33,"the quota derives from all eligible authored stories");h.assertTrue(WitnessAccount.Story.of("old_cabin")==null,"the recurring witness cabin is guidance, not another source");int sources=0;for(var place:LabyrinthPlace.values())if(LiteraryRooms.isLiterary(place)&&place!=LabyrinthPlace.OLD_CABIN){h.assertTrue(WitnessAccount.Story.of(place.id())!=null&&LiteraryTexts.source(place).has(DataComponents.WRITTEN_BOOK_CONTENT),"every new eligible site has original discovery writing and its own resolution registration");sources++;}h.assertTrue(sources==23&&WitnessAccount.Story.values().length-1>=WitnessAccount.REQUIRED,"one optional closure leaves forty-two sources for thirty-three required resolutions");for(var story:WitnessAccount.Story.values())WitnessAccount.resolve(data,player,story,"resolved");h.assertTrue(WitnessAccount.count(data,player)==43&&WitnessAccount.ready(data,player),"different choices in one story cannot add a second source");h.succeed();}
    @GameTest(template="empty",batch="literary_copy",timeoutTicks=500)
    public static void anActualSleptHomeCreatesPrivateFrozenCopiesWithEmptyOriginalContainers(GameTestHelper h){var f=new Fixture(h);var p=f.player("copy_reader",LabyrinthPlace.HILL_NURSERY);var peer=f.player("copy_peer",LabyrinthPlace.HILL_NURSERY);var world=p.server.overworld();var home=new BlockPos(63500,80,63500);var bed=home.offset(2,0,-3);LiteraryRooms.box(world,home,-32,-1,-32,31,-1,31,Blocks.STONE_BRICKS);NovelRooms.room(world,home,-10,10,-10,10,0,6,Blocks.OAK_PLANKS,Blocks.BIRCH_PLANKS);NovelRooms.door(world,home.offset(0,0,10),Direction.SOUTH,Blocks.OAK_DOOR,false);NovelRooms.bed(world,bed,Blocks.WHITE_BED,Direction.NORTH);world.setBlock(home.offset(-5,0,-3),Blocks.CRAFTING_TABLE.defaultBlockState(),3);world.setBlock(home.offset(-4,0,-4),Blocks.CHEST.defaultBlockState(),3);((ChestBlockEntity)world.getBlockEntity(home.offset(-4,0,-4))).setItem(0,new ItemStack(Items.DIAMOND,7));world.setBlock(home.offset(5,0,-5),Blocks.PISTON.defaultBlockState(),3);world.setBlock(home.offset(7,0,-5),Blocks.HOPPER.defaultBlockState(),3);world.setBlock(home.offset(6,-1,-5),Blocks.FARMLAND.defaultBlockState(),3);world.setBlock(home.offset(6,0,-5),Blocks.WHEAT.defaultBlockState(),3);
        h.runAfterDelay(10,()->{p.teleportTo(world,home.getX()+.5,home.getY(),home.getZ()+11.5,180,0);p.hasChangedDimension();var door=home.offset(0,0,10);NeoForge.EVENT_BUS.post(new PlayerInteractEvent.RightClickBlock(p,InteractionHand.MAIN_HAND,door,new BlockHitResult(door.getCenter(),Direction.SOUTH,door,false)));world.setDayTime(18000);p.moveTo(bed.getX()+.5,bed.getY(),bed.getZ()+1.5);p.startSleeping(bed);});
        h.runAfterDelay(100,()->{p.stopSleepInBed(true,true);var family=LiteraryCopies.base(p.server,p.getUUID(),LabyrinthPlace.FAMILY_COPY);var cabin=LiteraryCopies.base(p.server,p.getUUID(),LabyrinthPlace.OLD_CABIN);h.assertTrue(family!=null&&cabin!=null,"real native sleep captures and constructs both independent bounded snapshots");h.assertTrue(LiteraryCopies.base(p.server,peer.getUUID(),LabyrinthPlace.FAMILY_COPY)==null,"an unslept peer receives no borrowed home");h.assertTrue(LiteraryCopies.prepareEntry(p,LabyrinthPlace.FAMILY_COPY)==null,"the family waits two actual in-game weeks");var chest=(ChestBlockEntity)f.out.getBlockEntity(family.offset(-6,0,-35));h.assertTrue(chest!=null&&chest.isEmpty(),"the actual copied container is empty while the seven source diamonds remain in the native home");h.assertTrue(((ChestBlockEntity)world.getBlockEntity(home.offset(-4,0,-4))).getItem(0).getCount()==7,"capture never takes source property");h.assertTrue(f.out.getBlockState(family.offset(3,0,-36)).is(LiteraryRegistry.FROZEN.get()),"the actual captured piston uses its inactive original mesh");h.assertTrue(f.out.getBlockState(family.offset(5,0,-36)).is(LiteraryRegistry.FROZEN.get())&&LiteraryFrozenBlock.original(f.out,family.offset(5,0,-36)).is(Blocks.HOPPER),"the captured hopper retains its native state without a ticking inventory or overwritten display data");world.setDayTime(14*24000L+18000);});
        h.runAfterDelay(115,()->{var family=LiteraryCopies.base(p.server,p.getUUID(),LabyrinthPlace.FAMILY_COPY);h.assertTrue(LiteraryCopies.prepareEntry(p,LabyrinthPlace.FAMILY_COPY)!=null,"maturity opens this reader's exact private entry");p.teleportTo(f.out,family.getX()+.5,family.getY(),family.getZ()-3,180,0);p.hasChangedDimension();LiteraryVignettes.onArrive(p,LabyrinthPlace.FAMILY_COPY);var chestAt=family.offset(-6,0,-35);p.moveTo(chestAt.getX()+.5,chestAt.getY(),chestAt.getZ()+2.5);var locked=new PlayerInteractEvent.RightClickBlock(p,InteractionHand.MAIN_HAND,chestAt,new BlockHitResult(chestAt.getCenter(),Direction.SOUTH,chestAt,false));NeoForge.EVENT_BUS.post(locked);h.assertTrue(locked.isCanceled(),"the empty copied chest is natively locked instead of accepting the visitor's property");f.source(p,LabyrinthPlace.FAMILY_COPY);var original=f.own(p,LabyrinthPlace.FAMILY_COPY).getCompound("Original_Source").copy();var copies=LiteraryCopies.get(p.server);p.server.overworld().getDataStorage().set("the_oldest_house_literary_copies",LiteraryCopies.load(copies.save(new CompoundTag(),p.registryAccess()),p.registryAccess()));h.assertTrue(family.equals(LiteraryCopies.base(p.server,p.getUUID(),LabyrinthPlace.FAMILY_COPY)),"native SavedData reload retains the private address and completed build cursor");f.source(p,LabyrinthPlace.FAMILY_COPY);h.assertTrue(original.equals(f.own(p,LabyrinthPlace.FAMILY_COPY).getCompound("Original_Source")),"copy readers keep the same finite paper after reload");try{ArchitectureTests.export(f.out,family,LabyrinthPlace.FAMILY_COPY);ArchitectureTests.export(f.out,LiteraryCopies.base(p.server,p.getUUID(),LabyrinthPlace.OLD_CABIN),LabyrinthPlace.OLD_CABIN);}catch(Exception e){throw new IllegalStateException(e);}h.succeed();});}
    @AfterBatch(batch="literary_copy") public static void copyDone(ServerLevel l){close();}
    @GameTest(template="empty",batch="literary_cabin",timeoutTicks=300)
    public static void theActualNamedOfferingIsSealedOnceAndTheOwnTelevisionAccountMustBeRead(GameTestHelper h){var f=new Fixture(h);var place=LabyrinthPlace.END_WORLD_CABIN;var p=f.player("cabin_reader",place);var peer=f.player("cabin_peer",place);f.build(LabyrinthPlace.HILL_NURSERY);f.data().visit(p.getUUID(),LabyrinthPlace.HILL_NURSERY);f.source(p,place);f.at(peer,place,0,0,-5);var offering=new ItemStack(Items.COMPASS,2);offering.set(DataComponents.CUSTOM_NAME,net.minecraft.network.chat.Component.literal("The last way home"));net.minecraft.world.item.component.CustomData.update(DataComponents.CUSTOM_DATA,offering,t->t.putInt("Original",173));var expected=offering.copyWithCount(1);p.getInventory().selected=8;p.setItemInHand(InteractionHand.MAIN_HAND,offering);f.click(p,place,LiteraryRooms.TV);h.assertTrue(p.containerMenu instanceof LiteraryChoiceMenu,"the actual television opens an explicit native offering dialogue");p.containerMenu.clicked(0,0,net.minecraft.world.inventory.ClickType.PICKUP,p);var own=f.own(p,place);h.assertTrue(own.getBoolean("Offered")&&p.getMainHandItem().getCount()==1,"only the explicitly offered native item is consumed");var kept=MotherCollection.get(p.server).entry(own.getUUID("Offering"));h.assertTrue(kept!=null&&kept.sealed&&ItemStack.matches(expected,ItemStack.parseOptional(p.registryAccess(),kept.contents)),"permanent custody retains every original native component");h.assertTrue(own.getIntArray("Screen").length==384&&own.getString("ScreenRoom").equals("hill_nursery"),"the television keeps a bounded actual view of this reader's visited room");h.assertTrue(!LiteraryCabinChoices.choose(p,0,null)&&p.getMainHandItem().getCount()==1,"the choice cannot consume a second original");f.at(p,place,7,0,-21);f.look(p,f.base(place).offset(LiteraryRooms.TV));h.runAfterDelay(220,()->{h.assertTrue(f.own(p,place).getBoolean("Ready")&&!f.own(peer,place).getBoolean("ChoiceMade"),"only the chooser's actual screen examination earns an ending");f.read(p,place,LiteraryRooms.ending(place));h.assertTrue(WitnessAccount.has(f.data(),p.getUUID(),WitnessAccount.Story.END_WORLD_CABIN)&&!WitnessAccount.has(f.data(),peer.getUUID(),WitnessAccount.Story.END_WORLD_CABIN),"reading the owned choice record resolves only its reader");h.succeed();});}
    @AfterBatch(batch="literary_cabin") public static void cabinDone(ServerLevel l){close();}
    @GameTest(template="empty",batch="literary_confession",timeoutTicks=3500)
    public static void theActualCarriedQuillResumesAcrossVisitsAndTheSealedJournalIsReadPersonally(GameTestHelper h){var f=new Fixture(h);var place=LabyrinthPlace.CONFESSION;var p=f.player("quill_reader",place);f.source(p,place);p.getInventory().add(new ItemStack(Items.WRITABLE_BOOK));f.at(p,place,1,0,-18);f.look(p,f.base(place).offset(1,1,-22));journalChapter(h,f,p,0);}
    private static void journalChapter(GameTestHelper h,Fixture f,ServerPlayer p,int chapter){h.runAfterDelay(360,()->{var place=LabyrinthPlace.CONFESSION;var own=f.own(p,place);h.assertTrue(own.getInt("Chapter")==chapter+1,"actual present speech advances one complete chapter, then waits for a return");if(chapter<7){h.assertTrue(p.getInventory().countItem(Items.WRITABLE_BOOK)==1,"the same carried native quill remains through the spoken chapters");f.arrive(p,place);f.at(p,place,1,0,-18);f.look(p,f.base(place).offset(1,1,-22));journalChapter(h,f,p,chapter+1);}else{h.assertTrue(p.getInventory().countItem(Items.WRITABLE_BOOK)==0&&own.contains("SignedJournal")&&!own.getBoolean("Ready"),"the actual quill is sealed once, without earning an unread ending");f.arrive(p,place);f.read(p,place,new BlockPos(10,1,-29));h.runAfterDelay(10,()->{h.assertTrue(f.own(p,place).getBoolean("Read_Journal")&&f.own(p,place).getBoolean("Ready"),"personally reading the exact sealed journal resolves the later return");f.read(p,place,LiteraryRooms.ending(place));h.assertTrue(WitnessAccount.has(f.data(),p.getUUID(),WitnessAccount.Story.CONFESSION),"the owned final account yields this one source");h.succeed();});}});}
    @AfterBatch(batch="literary_confession") public static void confessionDone(ServerLevel l){close();}

}
